### PR TITLE
add start function

### PR DESCRIPTION
**Pull request by vertexi**
I found that there is a stop function, but have not a start function, to continue playing music.
I hope this PR is useful.

### CODE REVIEW

**Comment by james1236** [comment]
Thanks for the pull request! I don't have the hardware with me to test this, but from a quick look I see you're setting

`self.pwms = []`
 
  without doing 
  
 ```
 for pwm in self.pwms:
            pwm.deinit()
 ```

Maybe this could be a memory leak or not ideal in some other way?

**Comment by vertexi** [comment]
Thank you for the mention.:smile: I have done that fix.

**Comment by james1236** [comment]
Very quick, thank you! 😄

I think a better name for `start()` would be `restart()` and a better name for `continue_music()` would be `resume()`

Final thing, does the loop code need to be in `continue_music()`? Won't that be done in the next tick anyway?

```
if (self.timer % (self.tempo * self.end) == 0 and (not (self.timer == 0))):
    self.beat = -1
    self.timer = 0
```

**Comment by vertexi** [comment]
You are right! Done.

**Comment by james1236** [comment]
Great, thanks for helping out! 😄

**Pull request merged**
